- README.md
> Fixed typo in config example.

- quickemu
This enables one to override the automatic selection of RAM and CPU resources.
> Fix #21 configurable RAM and #22 configurable cores

- quickemu
allows to run more VMs in parallel
> find free port for spice

- README.md
- quickemu
Have added a --fullscreen flag so VM can be run in full screen if so desired.
If fullscreen is applied, monitor x and y resolution are determined in order to resolve mouse syncing issue.
> Fix #32 Added fullscreen option

- README.md
- quickemu
Hi all,
as I use VMs sometimes to run software, that should not be able to read my `${HOME}` I added a flag to disable the SMB sharing.
As this is may be a use case for others I thought I will share it ;-)
Best Regards,
Ben
> Added Basic SMB Managment

- quickemu
ERROR! Qemu 6.0.0 is newer is required => ERROR! Qemu 6.0.0 or newer is required
> Fixed a typo

- README.md
While installing MacOS in Quickemu, I noticed a few things that needed to be updated in order to get to the inteded result.
> Fixed : updated instructions to install MacOS

- quickemu
The option is -full-screen and not --full-screen, and should not be part of the -device option
> Fixed : -full-screen option to qemu

- quickemu
See https://github.com/wimpysworld/quickemu/issues/107#issuecomment-951943497
> fix for virtio-vga-gl to be usable

- quickget
Added support for x86 versions of android.
https://www.android-x86.org/
> Android Support

- .github/workflows/greetings.yml
Make the name of the Greetings GitHub Action more friendly by adding a waving hand emoji.
> Add a waving hand emoji to greetings GitHub Action

- quickget
Support for the centos clone Rocky Linux. this adds test involvement red hat compatibles system.
> Rocky Linux Support

- quickemu
> fix for shortcut presumption

- quickget
Adding Solus support
( heads up to https://github.com/Lukewh/quickemu-icons/issues/12 )
> Support for Solus added

- README.md
- quickget
focal and hirsute versions of Release 1.6.0
plus hirsute and impish based pre-release 2.0.0
> Added support for Regolith Linux

- quickget
fixes #212 
check if zsync is in the path and fallback to wget within zsync_get and list_csv
Thanks to @daPhipz for helpful discussion and contributions.
> Fix 212 Fallback to wget if zsync not available

- quickget
Missing android sections replaced.
Fixes #219
> Android option working

- quickemu
Removed double definition of virtio-serial-pci.
> Removed double definition of virtio-serial-pci

- README.md
- quickget
https://github.com/Lukewh/quickemu-icons
> Add .png and .svg icons to the CSV and JSON lists. Close #183

- quickget
fixes #239
Temporarily need to not get the latest latest Win11 build as it isn't there
> Go back one Win11 version

- quickget
New version posted by Rocky Linux on November 15, 2021
> Add version 8.5 to Rocky Linux

- README.md
- quickget
> Add Oracle Linux support

- quickget
and any typos I spot (or make!) that haven't been picked up already
> Mainly pacification of shellcheck

- quickget
> Missing rocky appearance in final catalog

- quickemu
This adds a display option in the conf file such that user can specify the display method they want without using `--display`
> add a display setting in the conf file

- README.md
- quickemu
Fixes #115 via re-imposition of #132
> Re-disabled network for re-appearance of #115

- README.md
Added to the usage() summary but not the copy in the README
> Some new features needed adding to the README

- quickget
[Release Announcement](https://nixos.org/blog/announcements.html#21.11)
> NixOS: add 21.11

- quickget
The ElementaryOS  ~6.0~  6.1 ISO has been revved and renamed
> New release of elementaryOS 6.1

- README.md
- quickget
Hope I have added everything the right way.
I was able to download the iso on my end.
> add arcolinuxl iso to the list

- README.md
- quickemu
- quickget
Adding Haiku Beta 1 R3 support to quickget and quickemu.
> Add Haiku support

- quickget
As i was **whimping** up a debian VM I Noticed it was at version 11.1.0. changed it to the latest release 11.2.0
> Update Debian version to 11.2.0

- README.md
- quickget
> Add Alpine Linux support

- quickemu
- quickget
- #305
- #309
- #330
closes #306 #330
> Merging fixes - Consolidated PR of some pending bug fixes

- quickget
> Add suport for aria2c for faster downloading if installed

- README.md
- quickget
-optional parameters added
--localiso (if not supplied will use the distro/download filename
--isodir search root for find ...
copies in the first file found then carries on with wget/zsync
Also gathered the other parameters into the same fold.
Added usage() for --help (no parameters at all still behave as before since I think that is better UX)
> Use local isos

- README.md
I think this is the only thing that **needs** fixing.  The excellent chat contribution from @m1ga caught the other issues.
If further review finds more issues I'll dot them on here. There'll be another PR tonight for "cosmetic" issues that were left.
> Replace BSD note.

- README.md
- quickget
> Pretty name corrections

- README.md
- quickget
TIL how to do search replace in variables - never to old to learn new tricks.
> Debian netinst nonsed

- README.md
As I learned today on the Discord server.
> A little README help for SSH access into a headless VM

- quickget
> Respect edition param when quickgetting freebsd

- quickget
update debian upstream version 11.3.0
Log:
> fix: update debian upstream version 11.3.0

- quickemu
> Additional OVMF paths for recently updated Solus hosts

- quickget
> add support for EndeavourOS

- quickget
8.4 removed and 8.6 and 9.0 releases added
> Update Alma releases

- quickget
NY set as it seemed good enough.  Other working options left in comments in case
> changed haiku mirror as cdn no longer resolves

- quickget
> feat: add deepin support

- quickget
> Make Fedora 36 available

- quickget
> add Mint Release 20.3

- quickget
Pretty straightforward. Tested with Intel edition.
> Support Pop!_OS 22.04

- quickget
omit from visible list but leave in hidden `eol-..` options
> Remove Impish at EOL 14/7/2022

- quickget
> Add 11.4.0 current live release

- quickget
also reflect changed name for dvd iso
closes #505
> Update latest Rocky to 9.0 release

- quickget
update cachyos release and edition structure
fixes [465](https://github.com/quickemu-project/quickemu/pull/465)
> new release CachyOS

- quickemu
This is a rebase of https://github.com/quickemu-project/quickemu/pull/472 with
conflicts fixed, and an option to turn off 3d acceleration which can have
issues, especially with nvidia cards.
> Add support for spice-app

- windowskey
@wimpysworld - Just knocked this out while you were on stream. Check the URL, I didn't catch it when you showed it, so could have found the wrong page.
Run it with `./windowskey -h`.
> Add script to retrieve Windows product keys

- quickget
> Add super-size for some Zorin options

- quickemu
Add udp port forward, which can be useful for windows rdp udp acceleration.
> Add udp port forward

- quickget
Added Linux Mint 21 in `function_releases_linuxmint()` in quickget.
> added Linux Mint 21

- README.md
Very subtle but important typo 😊
> Small README Typo in first example

- README.md
- docs/quickemu_conf.1
- docs/quickemu_conf.1.md
> Incorporate additional changes into generation

- quickget
A little bit of cunning code needed to avoid this routine break/fix. My effort at that is in #547 which obsoletes this.
> debian 11.5 and 10.13 released

- README.md
As recommended in https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/#user-content-quick-summary.
> Replace shallow clone with partial clone

- README.md
- docs/quickemu.1
- docs/quickemu.1.md
- docs/quickemu_conf.1
- docs/quickemu_conf.1.md
- docs/quickget.1
- docs/quickget.1.md
README and man pages regenerated incorporating documentation updates from Release 4.4
> Regenerated docs for 4.4 Release

- quickget
Release availability made dynamic
fixes #576
> FreeBSD 13.1 released

- quickget
> Alma released 8.7 and 9.1-beta-1 also added

- quickget
Including the addition of Fedora 37 in a separate pull request as requested 😄
> added fedora 37

- README.md
- quickget
This supersedes #579
Please let me know if anything needs fixing 👍🏻
> Adding ubuntu unity

- quickget
Adds the more recent 2022 releases for Endeavour OS.
> add endeavouros releases up to 22_12

- quickget
Added support for RebornOS, tested and working.
> Added support for RebornOS in quickget

- README.md
- docs/quickemu.1
- docs/quickemu.1.md
- docs/quickemu_conf.1
- docs/quickemu_conf.1.md
- docs/quickget.1
- docs/quickget.1.md
> chore: regenerated docs for release

- quickget
> Alma 9.1 is released

- quickget
> updated cachyos release

- quickget
> Update mxlinux to current release

- quickget
> Updated for release of Rocky Linux 9.1

- quickget
Closes #681 
And accommodates Lunar (23.04) release.
> Add support for Lunar 23.04 and add Ubuntu Cinnamon flavour

- README.md
- docs/quickemu.1
- docs/quickemu.1.md
Taken from :
eagavi/quickemu@88682d2
Co-authored-by: eagavi <eagavi@users.noreply.github.com>
> Correction of debian dependencies

- README.md
- docs/quickemu.1
- docs/quickemu.1.md
- docs/quickemu_conf.1
- docs/quickemu_conf.1.md
- docs/quickget.1
- docs/quickget.1.md
- quickget
Closes #640 
https://github.com/quickemu-project/quickemu-icons/issues/12
> added BlendOS

- quickget
Another void spin got new version so...
[VX Linux](https://github.com/dessington/vx-linux)
> Add VX Linux

- quickget
HoloISO
SteamOS 3 (Holo) archiso configuration.
to your VM
[project](https://github.com/theVakhovskeIsTaken/holoiso)
Download is too slow...
will need some refactoring?
> Add SteamOS HoloISO

- README.md
one day I'll find the magic or remember to do this while chasing the stream
> remove cog stutter

- quickget
closes #644 
( and reminded/encouraged by #694 )
> Add Vanilla OS

- quickget
Also try and support the `-legacy` and `-canary` options, although they seem to come and go
> Daily-live images need more space

- quickemu
After updates to the upstream I wasn't able to merge changes into my fork (I must have messed things up) I deleted my fork and re-forked and redid my changes for this and am resubmitting
> Issue 650 - Allow --screenpct which will scale VM's screen size

- quickemu
I had a typo in first pull request sorry
> Issue591 - line breaks in generated script

- quickget
[XeroLinux](https://xerolinux.xyz/)
Initial commit..
As you asked..
Test pls. @TechXero
> Add XeroLinux

- README.md
- docs/quickemu.1
- docs/quickemu.1.md
Co-authored-by: dabrown645 dabrown645@users.noreply.github.com
> docs: additional note explaining --screenpct

- quickget
This PR fixes the releases for ArcoLinux.
> fix arcolinux releases

- quickemu
Will now work with nix / nixOS
Closes #722
Co-authored-by: omernaveedxyz  <omernaveedxyz@users.noreply.github.com>
> Improve test for presence of smbd

- quickget
Garuda Linux not work at all.
mirror is dead
Use cloudflare mirror
editions setted manually
disc_size 32GB
> garuda: fix

- quickget
> Add bunsenlabs

- README.md
- Added instructions on installing Quickemu on Arch linux and its derivatives in the README.md file.
> Added install instructions for arch

- quickget
> Add Linux Lite

- quickget
> Add Porteus

- quickget
> holoiso: update

- quickemu
Added support to resize screen like available for x11 - also reformatted section to standard 4 space indentation
> resizing screen support for wayland like available for x11

- README.md
- quickget
This implementation is based on Mido:
- https://github.com/ElliotKillick/Mido
More useful failure messages are presented and if the download is blocked clear steps to manually complete the setup are presented. Windows 8 is re-instated as a supported release, although without install automation or driver optimisation.
> feat: restore automated Windows .iso downloads from Microsoft servers

- quickget
- Add exception for Fedora Onyx ( new in fedora 39 )
> Add Fedora 39

- README.md
Not sure how you feel about this but thought this would save you some time.  
It's all neutrally worded and follows the same pattern as the quickgui entry.   I thought the small screenshot brightened up that section of the readme and helped convey a general sense of GUI to both references in that topic.
How this is meant to dovetail with the other two readme files in the docs section left me a bit puzzled. But I saw that other readme PR's had been accepted on just a single edit, so I went with that.  It is only a single change, at one point, so quite easy to paste ...
Fixes issue #803
> add qqX to the main  quickemu readme (hopefully)

- quickemu
I have redone the quickemu for 4 space indentations. I couldn't figure out how to do the merge with my last request and know I wasn't making a mistake.
> Redo of quickemu indentation - no code changes.

- quickget
> List ubuntu-server releases and hide eol releases

- quickget
> add PureOS

- quickemu
https://github.com/quickemu-project/quickemu/pull/875
> fix: failing to launch VMs from outside directory

- .github/workflows/reviewdog.yml
> ci: reviewdog

- quickget
More functions not in correct position, but only this inside something else
- To the rest we will get later.
> FIX: quickget BROKEN!!! help_message function placement

- quickget
> chore: Whitespaces removal - no better readibility

- quickemu
was only taking the opening quote
> fix: small typo in sed call

- quickget
find chunkcheck anywhere in path
closes #1121
> fix: relocatable chunkcheck

- quickget
Live ISO based on Arch.
To test out nwg-shell on hyprland or sway
> feat: Add nwg-shell

- README.md
- debian/control
- docs/quickemu.1.md
- quickget
See the following for more information:
- https://github.com/quickemu-project/quickemu/pull/1087
- https://github.com/quickemu-project/quickemu/pull/1133
> chore: remove wget

- quickget
> Fix --url exiting with no output when provided release/edition parameters

- package.nix
reflect changes made elsewhere
> docs: Consistent description for package.nix

- README.md
Also, presuming you intended to indent the added reference I've made the indent conform so it should now render as intended.
> docs: correct small typos in README.md

- debian/control
- devshell.nix
- docs/quickemu.1
- docs/quickemu.1.md
- docs/quickget.1
- docs/quickget.1.md
- package.nix
required for quickreport
Todo:
> fix: add pciutils dependency

- quickget
Added support fo Linux Mint's new version: 21.3
> chore(new supported release): Added support for Linux Mint 21.3

- quickget
only 3 editions now and far too messy to support legacy releases
> fix: Arcolinux completely changed releases

- package.nix
https://github.com/NixOS/nixpkgs/pull/323133
> fix(nix): include samba so file sharing works

- .github/workflows/test-build-quickemu.yml
- .github/workflows/test-quickget.yml
Add a new CI workflow to build and lightly test quickemu.
> ci: add test-build-quickemu.yml

- quickemu
With the current code, the file will never be created, it's a logic bug.
> fix: make function ignore_msrs_always work

- quickemu
add alternate test for /usr/sbin/smbd in case it is not in the user's PATH
- Closes #1409
> fix: extend search for smbd

- quickget
This adds support for downloading the latest OpenSuse Aeon iso.
> feat: Add support for OpenSuse Aeon

- quickget
Added support for Linux Mint's new version: 22
> chore(new supported release): Added support for Linux Mint 22

- quickget
introduced in
https://github.com/quickemu-project/quickemu/commit/aa285f0f6ec4a96d413793e06099b4da015950f3
> fix: open homepage

- quickget
Added the latest release from Haiku (r1beta5). I left the other two releases there since there are still on the archive.
> chore: Add Haiku r1beta5

- quickget
A new major release of elementary OS has been released
> feat: add support for elementary 8.0

- quickget
Add support for Mabox Linux
https://maboxlinux.org
> feat: Add Mabox Linux

- quickget
Fixed siduction due to name change
Should work with future releases
> fix(siduction): Update to Shine_on+

- quickget
> feat: Linux Mint 22.1 support

- quickget
> fix: correctly match editions

- quickget
Links to iso release point as requested by @arcolinuxz 
- Closes #1623
> chore: move arco to author-requested release source

- quickget
Please include a summary of the changes along with any relevant motivation and context.
- Closes #1530
> feat: Add PCLinuxOS to quickget

- quickget
Please include a summary of the changes along with any relevant motivation and context.
- Closes #
- Fixes #
- Changed Parrotsec OS urls
- Resolves #
> Fix: parrotos urls changed to new ones

- quickget
The upstream download site has changed so we need to adapt our search slightly to match the new presentation
- Resolves #1657
> fix: adapt openindiana release search to updated website

- quickget
Adds support for downloading FreeDOS 1.4.
> feat: Add support for FreeDOS 1.4

- .github/workflows/publish-release.yml
- quickget
Please include a summary of the changes along with any relevant motivation and context.
- Closes #
- Fixes # 
Changed Arch Linux download mirror cause rackspace mirror had old versions.
- Resolves #
> fix: Arch Linux Mirror
