- quickemu
Export LC_ALL=C to force free and friends back to English.
> Fix parsing RAM amount on non-English systems.

- README.md
- quickemu
Hi Martin,
Notes for feature usage:
`quickemu --shortcut --vm <VMNAME>.conf`
.desktop added to user profile `~/.local/share/applications` folder
The icon for virgil is used.
When the VM is --deleted, the .desktop file is removed.
Updated the README.md also.
I closed my first PR to re-submit my changes.
This Pull Request addresses some issues commented upon in my first PR
- Deleted the debug messages
- Now using quemu-virgil icon from the 'current' directory, not a specified
version's directory.
- Added a newline at the end of the file.
Regards,
Mark Crouch
> Added - Desktop Shortcut feature (2)

- quickemu
Some distributions like ArchLinux provide properly configured QEMU, with working virgil. On such installs it's pointless to install additional version of QEMU.
This pull request adds option "--system-qemu" to run VM's with distribution provided version of QEMU.
> Allow using installed version of qemu

- README.md
Direct users to run `snap connect qemu-virgil:audio-record` to prevent pulseaudio terminal spam.
> Update README.md to fix #25

- README.md
- quickemu
In order to run Home Assistant in a VM, I need certain ports to be forwarded from my machine to my VM, so I can access the web interface or the embeded MQTT server.
I've looked at how th USB passthrough was made and tried to replicate that for forwards.
> Enable arbitrary port forwarding via config file

- README.md
- quickemu
This option allows to select which screen is used to compute the window's size. 
Usefull when the main monitor is not the smallest one, and the VM doesn't need to be moved around. 
Also mandatory to make the fullscreen mode work properly.
> Feature : --screen command line option

- quickemu
The OSK parameter contains parenthesis, they need to be escaped in the shell scripts.
The vendor name, Wimpys World, contains a space. It needs to be double-quoted.
> Fixed : problem with the generated shell script.

- README.md
- quickget
The Zorin iso does optional self-validation on boot it seems, but no sign of a hash to check.
quickemu boots ok but (at least for me ) you need to pick the "safe graphics" options when the installer iso boots or you get a non-working black screen.
> Added support for Zorin OS

- README.md
- quickemu
* Force Windows VMs to use AHCI for the cdrom and hard disk devices.
* Re-enable networking during Windows installation.
Fixes #150
> Re-enable networking during Windows installation

- quickget
fix #199
code for beta left so when 36 beta appears just need to add it to the release list
> Fedora 35 released

- quickemu
Adding OVMF paths for Gentoo users.
Taken from package:
*  sys-firmware/edk2-ovmf
Latest version available: 202105-r1
Latest version installed: 202105-r1
Size of files: 2,573 KiB
Homepage:      https://github.com/tianocore/edk2
Description:   UEFI firmware for 64-bit x86 virtual machines
License:       BSD-2 MIT
* Contents of sys-firmware/edk2-ovmf-202105-r1:
/usr
/usr/share
/usr/share/doc
/usr/share/doc/edk2-ovmf-202105-r1
/usr/share/doc/edk2-ovmf-202105-r1/README.gentoo.bz2
/usr/share/edk2-ovmf
/usr/share/edk2-ovmf/EnrollDefaultKeys.efi
/usr/share/edk2-ovmf/OVMF_CODE.fd
/usr/share/edk2-ovmf/OVMF_CODE.secboot.fd
/usr/share/edk2-ovmf/OVMF_VARS.fd
/usr/share/edk2-ovmf/Shell.efi
/usr/share/edk2-ovmf/UefiShell.img
/usr/share/qemu
/usr/share/qemu/firmware …
> OVMF path for Gentoo

- quickget
fixes #204 
fix as in slightly dirty hack - but since quickget parameter handling is deliberately minimal at the moment, and it doesn't have its own version (yet?) this PR just catches "version" as OS (with up to 2 dashes) and goes gets the quickemu version.
:shrug:
> nasty version hack for quickget

- quickget
[KDE Neon](https://neon.kde.org) follows a rolling release model and provides several editions, each with a different level of testing vs stability (Unstable, Testing and User Edition).
On top, there is also a Developer Edition (Unstable plus some dev tools and libs preinstalled).
The reason I file this PR as a draft, is that I need help getting `zsync` to work. All files are located under https://files.kde.org/neon/images/user/current/ (replace "user" with the desired edition).
According to the `zsync` README in this directory, `files.kde.org` will always force a `https` connection, making it unusable for downloads with `zsync`. Instead, they suggest using a mirror - there is a nice webpage that shows you the nearest one at https://files.kde.org/neon/images/user/current/neon-user-current. …
> Add KDE Neon to quickget

- README.md
- quickget
Yet another set of rolling releases with a slightly convoluted method to resolve the file name.
The mirrors have a .zsync file so updated to use zsync
Supports the current set of "flavours": ( ticks have been installed )
> Garuda support added

- quickemu
however secureboot in OMVF isn't enabled in solus, solus will have to enable secureboot in their omvf package before that can be enabled.
> This adds OMVF support in solus

- quickemu
The correct separator is "|" and not ",".
> Fix case statement

- quickget
With the `quickemu-icons` project moving from me to the https://github.com/quickemu-project org, the public image URLs have also changed.
> Update icon urls from lukewh -> quickemu-project

- quickget
While talking with @ymauray we noticed that the `.svg` request was using the `png` path causing a 404.
> png != svg. Causes 404 for image urls

- README.md
- quickget
It is needed I feel.
This just finds the standard current releases (all DE options)
sorted similar to intel|nvidia for Pop! : standard or nonfree taken as options (or none)
nonfree not noted in the Readme as it doesn't mention intel/nvidia options either as far as I can see.
I think both need noting somewhere.
Could do with some refactoring around the DE options (like the windows languages but different, and applied here and to e.g. Garuda) but it is Friday night ....
> Add Debian support

- quickget
Turn off Hibernation in Windows to correct issue #162
I've had some success correcting the "every other boot lockup problem" with Windows guests.
I was able to fix the problem on my machine by launching a cmd prompt with Admin privileges in the Windows guest and typing:
powercfg -h off 
(this turns off hibernation and thus also turns off fastboot)
This PR is an attempt to automate this fix using the autounattend.xml file.
Someone more familiar with Windows automation should test this thoroughly.
(There may be a better way to do it.)
> Turn off Hibernation in Windows autounattend.xml

- README.md
- quickget
> Add CachyOS support

- README.md
- quickemu
- quickget
This is initial support for Gentoo Linux to quickget,it does download and boot.
> Initial gentoo support

- quickget
15.3 cannot be downloaded at all using the current code due to `openSUSE-Leap-15.3-DVD-x86_64.iso` not existing. It would appear that starting with 15.2, `openSUSE-Leap-${RELEASE}-DVD-x86_64-Current.iso` has been released with the most current revision for that version.
> Fix Recent openSUSE Leap ISO Location

- quickemu
Congratulations, quickget and quickemu are very cool.
Before adding the path I get:
`./quickemu --vm ~/VMs/quickemu/archlinux-latest.conf 
Quickemu 3.11 using /usr/bin/qemu-system-x86_64 v6.1.0
- Host:     "openSUSE Tumbleweed" running Linux 5.15 (skynet)
- CPU:      Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz
- CPU VM:   1 Socket(s), 1 Core(s), 2 Thread(s), 4G RAM
ERROR! EFI boot requested but no EFI firmware found.
Please install OVMF firmware.`
After the addition, I was able to start all VMs I've tried.
> Added openSUSE path for OVMF

- quickemu
- quickget
It can download and boot this OS. There is one requirement: 7z.
Its not completed yet (at least internet and sound dont work)
> Adding KolibriOS support

- README.md
- quickget
> Add Manjaro Support all editions

- quickget
Adds support for the stable release of Tails: https://tails.boum.org/
I had to add `boot="legacy"` otherwise it won't boot (neither ISO or IMG), not sure why.
> Add support for Tails Linux

- quickget
Fix for #306 - works for me on Fedora with wget but no zsync.
> Fix #306 - supply dir to web_get when using wget

- quickget
Pretty much the title says it all.
It simplifies the code and make it much shorter and easier to add new distros/OSs
Let me know if you have any questions
-DM
> Replace multiple if statements with case and OR

- README.md
Old links that were being happily re-directed update to point to new homes under https://github.com/quickemu-project/
> Project links updated to new common home

- README.md
came across this and thought it might be handy in the README.md
[![Packaging status](https://repology.org/badge/vertical-allrepos/quickemu.svg)](https://repology.org/project/quickemu/versions)
[![Packaging status](https://repology.org/badge/vertical-allrepos/quickgui.svg)](https://repology.org/project/quickgui/versions)
Badges can be [tweaked extensively](https://repology.org/project/quickemu/badges)
We may want to add a little disclaimer about the packaging. Either way it's handy to see where it is being found, and with a link to find who the maintainer is.
> Add convenient external repository packaging info

- README.md
- quickemu
fixes #307
Added parameter `--acc | --accessible | --accessibility` which if given `braille` ( or `brl ` )
with add parameters to invoke `Qemu` braille terminal support.
> Add support for braille terminal

- quickget
Now the excellent `case` refactoring by @the-mentor has made it in, and given all the potential fun maintaining the several lists of OS and OS flavours etc. , and given he added a catch-all default, it made sense to me to remove the list from the top of the `case`  and the chatty echo so that in future contributors have one fewer place to edit and there is one fewer location where all the merge collisions happen.
> Reduce future pain

- quickget
This works again.
Needs more indentation fixing to save sanity, but minimally changed for now since white space diffs seem to be upsetting github more than it should and I don't want to risk blocking any other PRs for silly reasons.  
To use/try this feature you must supply a base path as `--isodir`, beneath which `find` will hunt for your iso.  You can supply an optional `--localiso` parameter to give an alternate existing filename for which to search. 
Sadly it doesn't (yet) deal with the complexities of the windows fetching.
For macOS  `--isodir` need to point to a path containing RecoveryImage.dmg and RecoveryImage.chunklist for the supported macOS version.  Be careful to be more precise because it is doing a fairly indescriminate `find <here> -exec cp .. <there>` for those names, so …
> Use local isos fixed

- quickget
Quotes needed to  allow bracketed langs to match.
User still needs to wrap the LANG parameter in quotes.
This closes bug #250
> Fix all Language variations for Windows. Close #250

- README.md
- quickemu
Generated version of the README.md.  The github diff looks horrendous because of pandoc (and me) introducing some markdown "standards" in the generation but if you do a `diff --side-by-side` with this and the current one it is easier to see the effects.  Because this has been made from sliced parts and generated parts recombined with half and eye on re-using for on-line documentation and man pages a couple of re-orderings have proved useful.
The main difference, and reason for this PR  in advance of our discussion, is because this catches and includes all the new supported Guest OS flavours.
```Other Linux Guests					      |	## Other Linux Guests
------------------					      <
`quickget` also supports:					`quickget` also supports:
- `alma` (Alma Linux)					      |	  * `alma`
- `alpine` …
```
> Generated readme

- quickemu
I added this simple piece of code for any extra arguments one wants to use.
You just add extra_args variable to your vm conf file.
ex. add host disk partition
extra_args="-drive file=/dev/sdb2,cache=none,if=virtio"
This is the easiest way to "extend" quickemu functionality.
> Add extra_args option in vm conf file

- quickget
This switches from codenames such as `bionic` to version numbers such as `18.04. 
This is more consistent with other distros that quickget can download. It's also the commonly used parlance for releases of Ubuntu. Internally the codename is used, for sure, and is used in release identification in some configuration files, but marketing wise, release numbers are used, and always have been.
I have tested downloading all the Ubuntu releases that quickget currently supports after this change.
> switch to version numbers fixes #376

- README.md
- quickget
One more BSD to the collection!
> Add support for DragonFlyBSD

- .editorconfig
- quickemu
- quickget
Every time I'm making changes to quickemu and quickget, I find myself indenting things with the wrong number of spaces, because the convention used in this project differs from my default.
I've also seen inconsistencies and therefore commits reformatting the code. So I added some Vim rules at the end of the files and an .editorconfig file, hopefully this will help!
> Add some whitespace-formatting rules

- quickget
By default, progress is sent to stdout, which is buffered and cannot be proerly processed by `quickgui`
> Send progress to stderr

- quickget
* Ensure Ubuntu releases are all downloaded via HTTPS URLs
* Add eol-4.10 thru to eol-21.10 releases for Ubuntu
* Add special handling of MD5SUMS-only Ubuntu releases on old-releases.ubuntu.com
* Add detection of Ubuntu `*-install.iso` files for very early Ubuntu releases
Signed-off-by: Dani Llewellyn <diddledani@ubuntu.com>
> RFC: Add old/obsolete/eol Ubuntu releases (hidden by default)

- README.md
- quickget
Fixes #395
Also corrects some old examples in in Readme
Fixes #391
```bash
~/src/quickemu-project/quickemu/quickget ubuntu-mate daily-live
#################### 100.0% 2490.0 kBps DONE     
##############------ 74.6% 17.1 kBps         
#################### 100.0% 6783.3 kBps DONE     
verifying download...checksum matches OK
used 3288150016 local, fetched 1120187253
Making ubuntu-mate-daily-live.conf
To start your Ubuntu MATE virtual machine run:
quickemu --vm ubuntu-mate-daily-live.conf
```
> Workaround zsync http-only failures

- quickget
Opensuse .sha256 file containing pgp key, hence filtering that out needed.
and rockylinux hashfile had an extra .iso.manifest , which was not handled hence there were 2 hashes in the output
> fix get_opensuse and get_rockylinux hash

- quickemu
Solution to the booting problem discussed in #382 and elsewhere implementing the fix identified by @chasecovello  in https://github.com/quickemu-project/quickemu/issues/382#issuecomment-1059635250_
Also  fixed missing  "$" (causing flawed test to always be true) added to correct logic
> Fixed boot problems and logic correction in FreeDOS support. Fixes #382

- quickemu
- quickemu is now able to reuse the viewer even after you have been closed the viewer-application
- you can decide if you want to invoke an other viewer or if you want to use an alternative like ssh
- you can connect to qemu-monitor via telnet or socket
- you can send qemu-monitor commands on the fly, for example, you can shut down the system
- support for alternative keyboard (I had some trouble with usb-keyboard if you use grub with at_keyboard) and mouse
- support for serial, for example, to get erlier kernel output
- add support for usb 3.0
> Add some features

- quickemu
- quickget
by special request - awaiting confirmation from @popey ~~whether~~ but it now ~~boots~~ runs here.
Probably need user to run with spice and/or pass a controller through (because the UI is controller-centric! )
Confirmation or problems and suggestions welcome
> Add batocera

- quickget
fix: #429
Selects `iso` file lines to avoid confusion where `.img` files have appeared
> Add filter to choose iso files in daily-live

- quickget
This is a very small, unobtrusive change, which adds a single line to the beginning of the .conf files generated by `quickget`, and marks it as executable. This allows them to be run directly (i.e. `./macos-catalina.conf`.
> Add shebang to conf and mark it as executable

- quickget
* reformated quickget to use consistant 2 space indentation
* removed the vim config line so would respect .editorconfig
* updated .editorconfig to be consistant with quickemu
* updated garuda release function to support only latest release
* updated function editions_garuda to get valid editions from
distribution web site
* updated function get_garuda to use the garuda latest iso images
* also change the default disk_size to 32G as I got error that 16G was
to small when I tested
> Garuda update to quickget to support latest release

- quickget
For windows downloads hashes aren't validated via hashes. Let's at least
validate that downloads are coming from microsoft via https.
Signed-off-by: Steffen Dirkwinkel <me@steffen.cc>
> quickget: get_windows: validate that download url leads to microsoft cdn

- quickget
Just give explanatory error messages for known missing spins
> add warning for unsupported fedora spins

- quickget
Fixes #463
Add supports CentOS Stream
Includes CentOS Stream releases 8 and 9, editions 'dvd1' and 'boot'. 'dvd1' is the default.
> Add support for CentOS Stream

- quickget
requested in #482
will need another icon (or will it?) : heads-up https://github.com/quickemu-project/quickemu-icons/issues/12
> add support for Linux Mint Debian Edition (LMDE)

- quickemu
As the `ignore_msrs_alert()` is called if the guest is macOS or windows, perhaps windows should also be included to the MSRs alert comment.
> Updates MSRs alert comment to include windows

- README.md
The default configuration for windows 11 has `secureboot="on"` in it.
The readme is updated accordingly
> fix window 11 config example

- quickget
A new batocera release moved the supported release URL.
Rewritten to support current and prior two releases.
LAlso the current version is checked at runtime so when 35 arrives 34 will still work. 
Closes #511
> Correct batocera for release 34

- quickget
Some obsoleted 8.x releases also removed
Closes #514
> Oracle Linux 9.0 added

- quickemu
- quickget
Initial support for ReactOS
https://reactos.org/
VM configuration is based on upstream documentation for QEMU:
https://reactos.org/wiki/QEMU
Only latest released version is supported. I was not able to find a good solution to download nightly builds.
> Add reactos

- quickemu
the default for `usb_controller` is set twice in `quickemu` script.
Remove the second `usb_controller` default setting.
> Remove duplicate option (usb_controller)

- quickemu
Bind spice to localhost, preventing potential unauthorized access.
> Bind spice to localhost

- quickget
Fixes an issue where the mirror for android iso's seems to no support IPv6.
> Force IPv4 on android mirror

- quickget
As the daily-live and daily-canary releases point to "next release" builds it was not possible easily to spin up a 22.04.1 daily test iso to help with the testing for the delayed point release. This was my attempt at a solution. It adds a "jammy-daily" release that points to the current jammy daily live isos (which were the ones being requested for testing at the time of the call) .
It might be worth adding this to the "eol-" filter to remove it from general view but add a note to the documentation.
It will be worth adding the next LTS codename in before it enters the testing cycle.
> add support for  LTS daily-live testing for point releases

- quickget
This should dynamically pick up debian releases for a while.
closes #546
> fix for dynamically selecting debian releases

- README.md
- docs/quickemu.1
- docs/quickemu.1.md
- docs/quickemu_conf.1
- docs/quickemu_conf.1.md
- docs/quickget.1
- docs/quickget.1.md
Added later and missed documentation updates in 4.2 to builder and regenerated docs.
Include change from PR 548
- replace shallow with unblobby clone Catch up with macOS note from merged PR 559
- note on macOS filesystems
Co-authored-by: giladwo <giladwo@users.noreply.github.com>
Co-authored-by:  tinsami1 <tinsami1@users.noreply.github.com>
> Updated 4.2 Documentation

- quickget
Add support for Archcraft (as requested #530):
https://archcraft.io/
> Add Archcraft

- quickget
I've added the 22.10 release to `quickget`.
Since there's a local variable named `LTS_SUPPORT` I created `local INTERIM_SUPPORT="22.10"` to separately include non-eol interim releases.
> [quickget] added version 22.10 in `releases_ubuntu`

- quickget
The CDN we were using in QuickGet only carries version 7.0 and 7.1. By switching to a different CDN provided for the OpenBSD Community (listed on https://www.openbsd.org/ftp.html) we can regain access to version 6.8 and 6.9.
> OpenBSD: Fix download of versions 6.8 & 6.9

- README.md
- quickemu
Currently, the virtio specification does not include provision for the TRIM (aka DISCARD) command that allows a guest operating system to signal the disk hardware that blocks have become unused so that the underlying device may clear the physical data.
The TRIM/DISCARD command was introduced for SSD disks as an extension to the AHCI specification that is used in SATA systems.
With Virtual Machines we can use this command to tell QEMU's Qcow2 driver to reclaim unused space in the disk image. This ensures the disk image file is kept to the smallest size possible where without the TRIM/DISCARD command it grows to it's maximum configured size and never shrinks again when data is deleted.
> Switch to disk devices that support TRIM

- quickget
Void use new format for the base live image iso:
- https://repo-default.voidlinux.org/live/current/void-live-x86_64-20221001-base.iso
- https://repo-default.voidlinux.org/live/current/void-live-x86_64-musl-20221001-base.iso
> update links for Void

- quickemu
Fix for issue https://github.com/quickemu-project/quickemu/issues/594 that introduced by the commit https://github.com/quickemu-project/quickemu/commit/ddbbc23d3447ceb1503bf549a000e0cace5cc723
> use long hv-* attributes for qemu 6.0.0

- quickget
Pop!_OS 22.04 fails to install with 16G disk_size. With 32G it installs successfully.
> Fix Pop!_OS install

- quickget
Because there are many server Linux distributions and even some general-purpose Unix OSes. TrueNAS is an interesting server OS, where Core edition is based on FreeBSD and Scale version is based on Debian.
> Added initial support for TrueNAS.

- quickget
Hopefully I did this right. I tested locally, and it appears to download the 7.0 ISO correctly.
> Add elementary 7.0

- quickget
This gets to download and run the installers with a 32G disk.
The 1st/2nd disk and boot disk nonsense in the conf gets ignored.
I'll  remove it when I get a moment.
> Correct basic error to get to downloading isos

- quickget
#625 left 6.1 in but they have removed that from their download page so we can no longer get it
see #629
> Remove old release from elementary - they only present current release

- quickget
See #629 
Older isos are bzipped so until we handle that only current is available
> Update drgaonfly release to current

- quickget
With the default a fresh install has 3% disk space left which isn't much to work with and even worse once updates are applied.
> Add custom size for NixOS 

- quickget
This obsoletes #675 but in case that gets closed
here's an attempt to acknowledge a valuable heads-up.
Co-authored-by:  Kurt Kremitzki <kremitzki@users.noreply.github.com>
> Make NetBSD releases dynamic

- quickget
Also this searches the bzip2-compressed isos, giving access to all older releases.
if the ".bz2" is removed from the search (e.g. using an empty variable that can be populated with .bz2 somehow (  if [[ -n ${USE_BZIP2}  ]] ; then ... )   ) then the search only returns the current uncompressed ISO, but should pick up any new release
> Make dragonflybsd release dynamic

- quickget
[siduction](https://siduction.org/)
Welcome to siduction
Siduction is an operating system based on the [Linux kernel](http://www.kernel.org/) and the [GNU project](http://www.gnu.org/). In addition, there are applications and libraries from [Debian](http://www.debian.org/).
The name siduction is a play on two words. The word sid, which is the codename of Debian Unstable, and seduction in the sense of seduce.
So here it is...
> Add siduction

- quickget
[Endless 5.0.0](https://www.endlessos.org/os) has been released.
Yes they recommend a minimum of 32G.
Closes #643
> Add Endless OS

- quickget
If you have set a download directory in aria2's config, quickget will download files to the wrong directory. This overwrites that setting and downloads files to the correct location.
Quote from `aria2c(1)`:
> `-o, --out=<FILE>`
>   The file name of the downloaded file. It is
>   always relative to the directory given in
>   `--dir` option.
> Fix aria2 using wrong destination directory

- quickget
and also now having gnome and kde editions
fixes #698
> Fix: Account for BlendOS 23.04 images moving to sourceforge

- README.md
On Big Sur and up apple includes the VirtIO driver and therefore the install disk is named Apple Inc. VirtIO Block Device instead of  QEMU HARDDISK Media. This PR lets the documentation reflect that.
> Correct disk to format in Big Sur and up

- quickget
Hi, I saw an issue for rockylinux images. The images that the quickget was pulling had wrong URL, so I fixed it. Hopefully everything is fine and you will be able to merge it.
> fix url and iso name for rockylinux versions

- quickget
Rackspace's mirror network is geographically distributed.  Requesting the mirror.rackspace.com endpoint will point you at the closest mirror to your location.  It will even route you to the next nearest mirror in the case of an outage.  Hard coding this to the lon.mirror.rackspace.com endpoint forces every user to route through London, regardless of their location.
> Use geo-distributed mirror for Alma URL

- quickget
i spend a day to fix this problem :joy: 
before this patch, when we try `quickget macos ventura` it's download `Sonoma` version :joy:
> Fix ventura RecoveryImage download

- quickget
Downloading of  Ubuntu eol releases and hash verification fails as the text is not correctly parsed. This PR fixes the issue.
> fix ubuntu eol releases

- quickget
Closes #728 
Ugly set of Releases : 
```
Releases: plasma/1688424625 gnome/1688424211 deepin/1688423865 lxqt/1688423615 mate/1688423313 xfce/1688423053 cinnamon/1688422684 plasma/1687873468 gnome/1687872336 deepin/1687871428 lxqt/1687870883 mate/1687870186 xfce/1687869663 cinnamon/1687869060
```
but functional - almost - need to fix up RELEASE/EDITION name/path when the test iso finishes .. :facepalm: 
Edit: well it all works as is actually, albeit with unusual path structure.
> fix blendOS downloads again

- quickget
- Updated get_manjaro() implementation to support fetching latest released versions
- Added sway release
- Added choice to download minimal or full edition
EDIT: Tested working
> Updated manjaro fetching as migrated to new system 

- quickemu
As part of getting the OpenIndiana ISO to boot and install with the default settings, I found that it doesn't have Intel HDA support, which is currently the only sound hardware set up by quickemu. So I added a new option "sound_card" to set the virtual hardware to one of "intel-hda", "ac97", "es1370", "sb16", or "none".
OpenIndiana was changed to "ac97" by default, and I also changed FreeDOS to use "sb16" since as far as I know there's no HDA driver for DOS and Sound Blaster was widely supported. This should also support, for example, older versions of Windows (XP, Vista) that don't come with HDA drivers.
> Add support for changing virtual sound hardware

- quickget
> vx-linux: 5.5

- quickget
> holoiso: 20230626

- quickget
Gentoo DIGESTS file contains BLAKE2B and SHA512 hashes. Since BLAKE2B comes first in the file, it was incorrectly selected when checking SHA512 checksum.
> Fix Gentoo hash check in quickget

- quickget
old iso deprecated
added boot iso
changed mirror to official almalinux.org
versions 8 and 9 will download latest release
> repair alma linux

- quickget
show error when listing releases (twice): `grep: warning: stray \ before "`
> repair NetBSD releases

- quickget
show error when listing releases (twice): `grep: warning: stray \ before "`
> repair DragonFlyBSD releases

- quickget
> Add PeppermintOS

- quickget
> Add SpiralLinux

- quickget
after a week, macos servers change default mac os recovery image for old board id
this pull request retrieve new board id from [this project](https://github.com/acidanthera/OpenCorePkg/blob/master/Utilities/macrecovery/boards.json)
> change Board_id for ventura image

- quickget
When I download files greater than 2GB in size the download always fails around the 2GB mark.
So I have to resume the download. If the size is greater than 4GB the download stalls again. etc. etc...
Without the proposed changes the download just hangs.
The if statement never completes and thus quickget sees no error.
A rerun does the trick. So this is essentially trying to save the user from doing a rerun. If all tries fail, a rerun is required anyway.
I set --tries to 3, so that I can download up to 6 GB without have to rerun. I am not sure how large the different images are. The Ubuntu Desktop image is 4.7 GB and I believe the Windows image is around 5.5 GB. So 3 tries seemed reasonable.
The 10 seconds are chosen arbitrarily. It has to be something to trigger a retry.
Aria seems to …
> Have wget retry when download stalls for 10 seconds

- quickemu
The latest [4.9](https://github.com/quickemu-project/quickemu/releases/tag/4.9) missed update on the version variable in quickemu.
Could there be a bugfix 4.9.1 release?
> quickemu: fix version

- README.md
- docs/quickemu.1.md
- quickemu
**Issue:** 
Using remote-viewer locally on the host (ex: spice://localhost:5930) works, however using it remotely (ex: spice://192.168.0.10:5930) will not connect.
[See issue](https://github.com/quickemu-project/quickemu/issues/833)
**Code Changes:**
The following code changes add an additional parameter (--access). 
If this parameter is excluded the status quo remains and spice sessions can only connect from 127.0.0.1. The same outcome occurs if the "local" option is used (ex: --access local). 
If the "remote" option (ex: --access remote) is used then no IP restrictions are imposed and the spice IP address section is left blank, allowing access from any machine that your firewall would otherwise allow.
A third custom option is also permitted (ex: --access 192.168.0.52) which allows …
> Add additional "--access" parameter to allow remote access to spice session

- quickget
As the quickget download the latest Batocera version only it's more convenient to use "latest" instead of old versions
> Update batocera version in quickget

- quickget
no i didn't read : https://github.com/quickemu-project/quickemu/pull/370
so...
why not?
@philclifford
tested from external script quickfzf https://github.com/quickemu-project/quickemu/pull/773
new features:
quickget commands
`quickget --show-iso-url alpine latest`
or
`quickget -s bodhi 7.0.0 standard`
`quickget --test-iso-url alpine latest`
or
`quickget -t bodhi 7.0.0 standard`
`quickget --open-distro-homepage alpine`
or
`quickget -o vxlinux`
test and show URL needs more testing and implementing zsync..
Long list of obtained ISOs (from my fork):
<details>
<summary>Details</summary>
`https://sourceforge.net/projects/agarimos/files/Plasma/AgarimOS-Plasma-Dracula-Live-x86_64-6.3.13_1-20230913.iso
https://sourceforge.net/projects/agarimos/files/XFCE4/AgarimOS-XFCE4-Catppuccin-Live-x86_64-6.3.1 …
> quickget: new features

- quickget
Without also removing the old case comparing the last release with the requested etc the new code always generated a non-existant URL.
This seems to get the latest file again.
> fix: make revised batocera actually find the latest file

- quickget
New address
https://repo-default.voidlinux.org
> bugfix: quickget: void not working

- quickget
This should fix iso download commencing when using new `-s/-t` flags
Fixes #845 
@philclifford Can you test this?
> Fix -s/-t flags still downloading isos

- quickget
Quickget currently creates a directory before checking the values of the show-iso-url or test-iso-url variables. If either are called, directory is left empty and serves no purpose.
> Fix quickget creating empty directories while using show-iso-url or test-iso-url parameters

- quickemu
milliseconds, almost instant ...
fix for earlier pr which failed on new installs
if disk was not present #848
> revised health checker

- quickemu
Previously grepped for sse4_1
but specified sse4_2
Also needs TSX controls.
See comments at end of #886
As in:
```
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.hle [bit 4]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.rtm [bit 11]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.hle [bit 4]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.rtm [bit 11]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.hle [bit 4]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.rtm [bit 11]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.hle [bit 4] …
```
> fix sse41 contradiction and cpuid host warnings

- quickget
As requested by @zen0bit ...
:heart:
> Add Tuxedo OS

- quickget
Currently, quickget determines the blendos release/edition combinations using its RSS feed, and then prints them all out as releases. For example, you'll see output like this: `plasma/1688424625 gnome/1688424211 deepin/1688423865 lxqt/1688423615 mate/1688423313 xfce/1688423053 cinnamon/1688422684 plasma/168787346`.
This also causes significant issues, such as directory names including slashes, as seen in #995.
This PR proposes replacing this mess with just offering the user the latest release, and listing out the available editions instead. The latest release is determined by numerically sorting through every available release within the selected edition. The releases & editions cannot be listed separately, since each edition has different releases (which are based on epoch time). …
> Use only latest blendos release

- .github/workflows/reviewdog.yml
This generate too much noise in pull-requests making it is impossible to review changes. Will re-enalble when quickemu and quickget have zero sheelcheck issues
> chore: disable reviewdog for PRs

- quickget
Updated the windows download functions based on current [Mido](https://github.com/ElliotKillick/Mido/tree/main) but retained the language selection and hash checking for Windows 11.
> Refactor Windows downloading based on Mido

- quickget
The os_error_release function only prints the releases if an editions function does not exist. This fixes the error.
> Fix regression in the case of a missing release

- quickget
archcraft
archlinux
batocera
bunselabs
macos
manjaro
mxlinux
> style: Sort OS releases alphabeticaly

- quickget
Original HoloISO was discontinued, this replaces it with the new immutable version.
The user agent for macOS set here also was unnecessary and totally broken. That would set it to the macOS internetrecovery user agent only if the OS was not equal to macos, which is wrong, and curl's headers appear to 
override the user agent flag so it's completely unnecessary. Therefore, I've removed that as well.
Fixes #1062
> Fix HoloISO downloads

- quickget
This pull request adds some new web handlers that use `curl` by default:
- `web_pipe()`: Download a file from the web and pipe it to stdout
- `web_check()`: Checks if a URL is reachable; an alternative to `wget --spider`
- `web_redirect()`: Checks if a URL needs to be redirected and returns the final URL
- `web_get()`: Already existed to download a file from the web, but now uses `curl` by default
- `web_get()` will fallback to `wget2` and `wget` if `curl` fails. 
- Most ad-hoc calls to `wget` have been replaced with calls to the appropriate `web_*()` handlers.
- A separate pull request will be submitted that replaces `wget --spider` with `web_check()`.
- Downloads have been manually tested and releases/editions updated where appropriate.
- Several `releases_*()` and `editions_*()` …
> Make curl based web handlers and update all ISO downloaders

- quickget
Windows URLs are invalid every time when limited to the first 512 characters.
> Fix windows downloads

- quickget
#999 renamed the 'os_not_supported' function without changing the os_supported function to point to the correct one.
> Fix error on invalid OS selection

- quickget
Add `--header` support to `web_check()` and replace `wget --spider` with `web_check()`.  Also includes some minor macOS fixes.
`--test-isos` now returns `PASS` or `FAIL`.
> Migrate to web_check()

- quickget
(for new **run** script)
To not clutter PRs to much, and make things bit easier
(why have to constantly switch between issues?)
- Final help message (Less is More)
- Removed obsolete arguments also from run script
- feat: Rewrite list_isos function for one OS only
- feat: Rewrite test_isos function for one OS only
- Solve 'lists' in case instead in iffi
- feat: Fill empty fields in os_info with ' - '
- fix error_not_supported_os
- Rename tuxedo-os to tuxedoos
- fix: Update some names etc in os_info and added new ones
Also accepting PRs in my branch with your quickfix (Bigger changes or new feature in own PR)
So can be included in this PR and hopefully makes thing quicker and easier
(csv,json)
`  '--list-csv'|'-lc'|'list'|'list_csv'|'lc')`
`  '--list-json'|'-lj'|'list_json')`
Raised issue …
> Update pack 1

- quickget
The pull request refactors and updates various functions related to listing ISO URLs and checking if the ISO download URLs are valid.
You can now:
List all URLs for an OS via:
`quickget --url-all ubuntu`
Check all URLs for an OS via:
`quickget --check-all ubuntu`
It is also possible to run these tests for all support OS' via:
`quickget --url-all`
`quickget --check-all`
Here are the failed test from `--check-all`
```
FAIL: arcolinux-v24.05.11-large           https://mirror.accum.se/mirror/arcolinux.info/iso/v24.05.11/arcolinuxl-v24.05.11-x86_64.iso
FAIL: arcolinux-v24.05.11-small           https://mirror.accum.se/mirror/arcolinux.info/iso/v24.05.11/arcolinuxs-v24.05.11-x86_64.iso
FAIL: arcolinux-v24.02.01-large           https://mirror.accum.se/mirror/arcolinux.info/iso/v24.02.01/arcolinuxl …
```
> Refactor and updates to get most of the tests working

- quickemu
An inappropriate apostrophe had sneaked in. It's about to be remove when this is merged, and its fate is sealed already in the pending regenerated docs and man pages
> fix: correct incorrect use of apostrophe in help

- .github/workflows/test-quickget.yml
- quickemu
- quickget
This pull request makes Quickemu compatible with macOS hosts, meaning that `quickemu` can now be used to create and run virtual machines on macOS hosts.
Intel and Apple Silicon CPUs on the host are supported. However, Quickemu currently only has x86 OS images available, so Apple Silicon Macs are currently provisioned with x86 virtual machines. This will be addressed in the future.
In addition, this pull request significantly improves the compatibility and performance when running macOS guest VMs, particularly if your host has an Intel CPU. Thanks to @TuxVinyards and @lj3954 for their research in this area. 
- Close #447
- Close #784
- Close #1236
> feat: add support for running quickemu on macOS hosts

- quickemu
- quickget
- quickreport
When running `quickemu`, `quickget` and `quickreport` across different Linux distros and macOS, there are several portability issues with how `tail`, `head` and `grep` are invoked. 
This pull request addresses those issues. 
`quickreport` is also updated to work on macOS x86 and Apple Silicon.
Lastly, some CI jobs were getting wedged and consuming 360 minutes of runtime before being forcibly terminated. To address that, `web_check()` now has timeouts and retries, EOL Ubuntu releases are removed, Debian releases are limited to the latest release in a series, and some other distros cap the number of available releases.
> fix: resolve portability issues between Linux distros and macOS

- quickget
Updating quickget to add:
* nixos `24.05` release
* nixos `plasma6` edition
I'm on an archlinux system. I installed [quickemu from the AUR](https://aur.archlinux.org/packages/quickemu).
On my local system I edited `/usr/bin/quickget` which is where the script is dropped by the aur package.
```
$  quickget nixos 24.05 minimal
Downloading NixOS 24.05 minimal
- URL: https://releases.nixos.org/nixos/24.05/nixos-24.05.803.b3b2b28c1daa/nixos-minimal-24.05.803.b3b2b28c1daa-x86_64-linux.iso
####################################################################################################################################### 100.0%
Checking nixos-24.05-minimal/latest-nixos-minimal-x86_64-linux.iso with sha256sum... Good!
Making nixos-24.05-minimal.conf
Setting nixos-24.05-minimal.conf executable …
```
> feat: adding nixos 24.05 to releases_nixos

- quickemu
Functionality was split across several functions in e29173a16d5fb1546a725a28bc8973007b228bbe, so SPICE cannot be local anymore as it is also referenced in vm_boot.
> fix: don't declare SPICE as local within configure_ports. close #1240

- quickemu
- quickreport
Due to zsh auto completion of piping to `grep [0-9]` does not work. This patch fixes this problem by quoting `"[0-9]"`.
> fix: running quickemu and quickreport in zsh. close #1268

- quickget
Added support for:
- ParrotOS 6.1
Removed support for:
- ParrotOS 5.9
> chore(updated supported releases): Updated support for ParrotOS 6.1

- package.nix
Essentially, when you try and import the project directly with nix flakes, you receive a missing 'name' attribute error. This is because 'name' is supposed to be defined in stdenv.mkDerivation, but is not. I [looked into it](https://discourse.nixos.org/t/clarification-on-package-names-and-versions/9819/2) and found that `name` is actually `<pname>-<version>`, so I just added it.
Below are the before and after outputs of flake.nix using `nix flake show`:
> fix: Fixes nix flakes by adding version to package.nix

- quickget
Add the option to choose KDE or GNOME editions.
> fix: update bazzite to always get the latest stable release. close #1306

- quickemu
When RAM is not specified in the config and the min RAM is not met, quickemu tells the user to override the RAM amount and exits. If the user overrides the RAM, the script should allow the user to continue with a warning.
> feat(quickemu): allow overriding insufficient RAM error

- quickget
>  fix: update holoiso to only download the most recent release

- quickemu
Set the default network interface to e1000 on Windows Server to ensure networking functions post-install. Tested Windows Server 2012-R2, 2016, 2019 and 2022.
- Fixes #1315
> fix(windows-server): default to e1000 network device. fixes #1315

- quickemu
Boot Windows from CD/DVD prompts to "press any key" to boot from the ISO media. The patch attempts to press enter 5 times at one-second intervals when booting from ISO media, instead of badly guessing when to press the enter key once.
> refactor: attempt to press any key 5 times during Window boot from CD/DVD

- quickemu
Passing the `--kill` argument to `quickemu` did not kill running VMs. This patch determines if a VM is running and what its PID is early so that `kill_vm()` can operate correctly.
> fix: get VM PID early so kill_vm() works reliably

- quickemu
Arguments passed to `quickemu` when creating a shortcut are not preserved in the desktop launcher. This patch fixes that by building a string of option arguments that are used to create the `Exec=` in desktop shortcuts.
- Fixes #1285
> fix: pass relevant arguments to Exec when creating shortcuts. close #1285

- quickemu
According to qemu-img documentation, it is a no-op for other filesystems.
> feat: Disable copy on write for disk images on btrfs

- README.md
- quickget
The patch removes support for the following versions of Windows:
- Windows 8.1, which has been EOL since January 10, 2023.
- Windows 10 LTSC, which is intended for large-scale, long-term enterprise deployments and makes little to no sense for a virtual machine.
- The Windows 10 LTSC support in Quickemu also lacked VirtIO and automated installation.
- Regular Windows 10 is still available in Quickemu.
- Windows Server 2012 R2 which is EOL since October 10, 2023.
> chore: remove Windows 8.1, Windows 10 LTSC and Windows Server 2012 R2

- quickemu
Set RAM_HOST to a rounded integer value so tests do not fail and produce ugly warnings
- Fixes #1346
- Resolves #
> fix: get rounded integer RAM_HOST values

- flake.lock
- flake.nix
This updates the Nix flake to be consistent with the Quickgui flake and always track the Nixpkgs stable branch.
The builds tool in the Nix devshell track the 6-monthly stable branch of Nixpkgs for better predictability.
> refactor: update Nix flake to be consistent with the quickgui flake

- devshell.nix
- package.nix
This completes the fix for connecting to the QEMU samba share using Nix flake/devshell.
- https://github.com/NixOS/nixpkgs/pull/323133
> fix: patch samba detection in Nix flake

- quickemu
This patch modified `usage()` so that it does not always `exit 1`. However, actual error condition that result is displaying usage do now `exit 1` where appropriate.
The reason for this change is so that simple build/test CI jobs do not encounter a failure condition when legitimately requesting `./quickget --help`.
> fix: requesting --help is not an error

- devshell.nix
- package.nix
- quickget
This pull request replaces all use of `fold` (from ncurses) with `fmt` (from coreutils) so that ncurses is no longer a Quickemu dependency.
> refactor: replace all use of fold with fmt; no need for ncurses

- quickget
quickget calls and references quickemu. The patch adds `resolve_quickemu()` to locate where `quickemu` is; either in the PATH will a fallback to the current working directory.
- Resolves #1278
> fix: add resolve_quickemu() to quickget so it can locate quickemu

- quickget
Make sure to download the `iso` for Fedora Silverblue instead of the `ociarchive`
Fixes #1257
Result with this change:
```
$ ./quickget fedora 40 Silverblue
Downloading Fedora 40 Silverblue
- URL: https://fedora.mirrorservice.org/fedora/linux/releases/40/Silverblue/x86_64/iso/Fedora-Silverblue-ostree-x86_64-40-1.14.iso
```
Before the change
```
$ quickget fedora 40 Silverblue
Downloading Fedora 40 Silverblue
- URL: https://mirrors.xtom.ee/fedora/releases/40/Silverblue/x86_64/images/Fedora-Silverblue-40.1.14.ociarchive
```
> fix: download Fedora Silverblue iso instead of ociarchive file

- .github/workflows/test-build-quickemu.yml
Make the tests a bit more robust by actually creating and running a VM. We do this as part of the Nix build test because the Nix Installer action from Determinate Systems will attempt to enable KVM acceleration.
If KVM acceleration is available, this test will now attempt to create, run and kill and an Alpine VM.
> ci: actually test running a VM

- quickemu
Clean up the output to only display socket connection hints relevant to the tools installs. Prefers `socat` over `nc`; displays nothing is neither are available.
> refactor: display socket hints based on what tools are available

- quickget
- **refactor: move create_config function to the bottom**
- **refactor: move unattended win installation code inside function**
- **feat: add --unattended flag to --create-config to create unattend.iso (windows hosts)**
Ability to pass in `--unattended` to `--create-config` to create unattended.iso and download VirtIO drivers for Windows guests.
- Closes #1369
> feat: Improve quickget custom configurations, including unattended windows support

- quickget
Removed unneeded quotes that cause confusing `command not found` errors.
- Closes #1395
> fix: dequote editions pipe

- quickemu
Windows/ReactOS/DOS conventionally set the system RTC to local time, but Linux/UNIX/macOS use UTC. Guest systems that expect UTC and have the time zone set to local time will have the wrong system clock time at startup until they set the clock with NTP. This is especially an issue for disk images imported from or shared with another VM configuration that uses UTC for non-Windows guests.
Further, according to the QEMU man page:
> Enable driftfix (i386 targets only) if you experience time drift problems, specifically with Windows' ACPI HAL. This option will try to figure out how many timer interrupts were not processed by the Windows guest and will re-inject them.
This option thus seems unnecessary for other systems and may cause performance or timekeeping issues, so enable only for …
> Fix: set RTC to localtime only for Windows/ReactOS/DOS and UTC for all others

- quickemu
lscpu populates the sockets field with '-' if the number of sockets it's determined is equal to 0 (which is accurately treated as a null value). Replace this value with 1 to fix invalid values being passed to qemu. 
- Fixes #1428
> fix: Use 1 as default sockets value

- quickget
Moved the logic for Sparky to parse a mirror listing as a possibly more reliable source as suggested.
- Fixes #1405
> fix: get sparky info from mirror

- quickget
Previous if clause does not work with Bash version 5.2.15(1)-release (x86_64-pc-linux-gnu)
for OS="windows" and RELEASE="11"
(leads to missing `tpm="on"` line in .conf resulting file)
Fixes #1387
[x] Bug fix (non-breaking change which fixes an issue)
> fix: use double brackets for if clause with and & or concatenation

- quickget
this is an unsupported release now
Remove Pop!_OS 21.10 release
> remove popos 21.10

- quickget
resolve_quickemu has inelegant test logic with redundant duplicate usage of `command`. This refactors resolve_quickemu slightly to remove the redundancy. It also changes the local fallback test to look for an executable file rather than just a file.
> refactor: remove redundant code from resolve_quickemu()

- quickget
Two packages used PCRE syntax which is not supported by the BSD grep present on MacOS.
These changes move from '-P' to '-E' syntax.
- Resolves #1396
> fix:  Change greps for parrotsec and nixos to use flags acceptable to MacOS

- quickget
Updates to new cdn
fixes  empty  elements in urls  eg. https://mirror.cachyos.org/ISO/kde///cachyos-kde-linux-.iso
> fix: CachyOS downloads

- quickemu
Quickemu actualy don't even start if pulseaudio is not installed.
qemu-system-x86_64: could not stat pidfile /run/user/1000/pulse/pid: No such file or directory
ALSA should be working on QEMU :), a simple solution is to test if `pacmd` is
currently installed.
> fix: Use ALSA on systems without a PulseAudio daemon

- quickget
so Deepin 23 and  later are correctly adjusted.
- Resolves #1488
> fix(deepin):  Correct architecture insertion logic

- quickget
Increase virtual disk size to the minumum install size required.
See https://docs.bazzite.gg/General/Installation_Guide/Installing_Bazzite_for_Desktop_or_Laptop_Hardware/#minimum-system-requirements
> fix: increase default disk size for bazzite to 64GB minimum

- quickget
Use https instead of http where the download place supports it.
I checked all http:// links in quickget and changed those where a https would also work.
> fix: Use HTTPS URLs wherever possible

- quickget
fixes #1462
adjust the RELEASE to remove and replace the space a couple of fails remain due to combinations that are not available
fixes #1493 
Only available EDITIONs are presented (or tested) per RELEASE
> fix(fedora): handle the space in the beta release

- quickget
Fixes #1502
Make sure to download the `.iso` for Fedora Atomic Editions instead of the `.ociarchive` by checking the `.link` field for a regex match.
> fix(fedora): Check whether the link value contains an actual .iso file

- quickemu
Arch Linux's packagers have removed the 2MB OVMF images in a recent change (https://gitlab.archlinux.org/archlinux/packaging/packages/edk2/-/commit/75700baee1f5073d558029efc0e03612bedfc048). Quickemu does not currently include the paths Arch's packages install the 4MB OVMF images to, which results in a failure to launch any EFI VM. This resolves the issue.
- Resolves #1511
> fix: Add ArchLinux 4M OVMF paths

- quickget
Update download_windows_workstation function to use Microsoft's new JSON API to fetch skuid & url. The previous method no longer is functional.
- Resolves #1528
> fix(windows): Use new Microsoft JSON API to fix URL generation

- quickget
> feat: Add proxmox-ve

- quickget
Release 23 has been replaced by 24 on https://www.truenas.com/download-truenas-scale/, which causes downloads to fail.
Also update Endless OS while we are at it.
Please include a summary of the changes along with any relevant motivation and context.
Bug fix (non-breaking change which fixes an issue)
> fix: TrueNAS Scale download

- quickget
The static list included a release that has been removed and also  hard coded mappings for 2023 and 2024. This dynamically determines the latest two years and finds available releases in those years, so will still provide reasonable service next year.
> fix(easyos): move to dynamic release behaviour

- quickget
The latest Solus release has changed the naming of ISOs:
- Update all related functions to support the ISO name format used in the latest release.
- Use the directory listings in order to support more releases in the future.
> fix(solus): update Solus URLs

- quickget
In Microsoft's new JSON API to fetch skuid & url, the response are:
```json
{
"Skus": [
……,
{
"Id": "18474",
"Description": "Redstone Windows Consumer x64 OEM/Retail ZH-CN DVD9",
"ProductDisplayName": "Windows 11 24H2",
"Language": "Chinese (Simplified)",
"LocalizedLanguage": "Chinese Simplified",
"LocalizedProductDisplayName": "Windows 11  Chinese (Simplified)",
"ProductEditionName": null,
"FriendlyFileNames": [
"Win11_24H2_Chinese_Simplified_x64.iso"
]
},
……,
{
"Id": "18480",
"Description": "Redstone Windows Consumer x64 OEM/Retail en-us DVD9",
"ProductDisplayName": "Windows 11 24H2",
"Language": "English",
"LocalizedLanguage": "English (United States)",
"LocalizedProductDisplayName": "Windows 11  English",
"ProductEditionName": null,
"FriendlyFileNames": [
"Win11_24H2_English_x64.iso" …
```
> fix(windows): Fix the download of the Chinese Windows ISO.

- quickemu
- quickget
Use the "Mac-827FAC58A8FDFA22" board ID (MacBookAir8,1) to download the Sonoma BaseSystem.dmg file.
> According to https://github.com/kholia/OSX-KVM/commit/ad213b6c80cbe9fdcd661832bb2ade8ec2b47a76#diff-1685371f8911f8e43b5420735f31cd5ec4dc7aedd7978a010abe4913af16c16aR541
Resolves #1501
> fix(macos): Correct version user receives from quickget; add sequoia

- quickemu
> fix: Check for PipeWire as well as PulseAudio before falling back to ALSA

- quickget
Quickget relies upon specific parameters passed to curl in order to find or download various operating systems. User defined configuration could break this, such as by sending undesired headers or cookies, which could cause requests to be blocked, or as in the case of #1570, to set output flags which cause curl to attempt to download files to invalid or incorrect directories. This issue can be resolved by disregarding the curl configuration file for any and all invocations within quickget, achieved by passing the `--disable` command line flag.
- Resolves #1570
> fix: Disregard curl configuration

- quickget
Quickget was modified to only allow arcolinux versions with the major release being 24 and minor being 06 or above, due to a change in editions taking place at that point. This is no longer necessary, as the latest 5 releases are well past this change. Version 25 has been released and isn't matched by the current regex.
- Resolves #1574
> fix: Allow non-v24 arcolinux releases

- quickget
Invalid editions, releases, languages, and operating systems do not throw errors, causing nonexistent functions to be called or attempting to download files from invalid URLs. This fixes the issue by properly checking to see if a full match of the value is contained within the string (separated by spaces), and in the case of windows languages, if the array contains the passed value.
> fix: Correctly throw errors when an invalid option is passed

- .gitmodules
For users just cloning this, ssh is incontinent because of 
```
The authenticity of host 'github.com (140.82.121.4)' can't be established.                                                                                    
ED25519 key fingerprint is SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU.                                                                                
This key is not known by any other names.                                                                                                                     
Are you sure you want to continue connecting (yes/no/[fingerprint])? no        
Host key verification failed.                                                                                                                                 
fatal: Could not …
```
> chore: use https for git submodules to use CA PKI instead of SSH TOFU

- quickemu
Move the initialisation of the script to above the functions so that changes they might make (e.g. `configure_tpm`) are retained. 
- Fixes #1573
> fix: move creation of script before functions that may update it

- quickget
Correctly match parrotsec releases including an arbitrary number of digits (i.e. '6.3.2', as opposed to '6.3'). Also handle multiple digits in between period delimiters, to account for possible v10+, and match the forward slash at the end of the reference to ensure incomplete matches aren't presented to the user. 
- Resolves #1501
> fix: Better match parrotsec releases

- quickemu
This change contains two fixes which ought to take the functionality of Secure Booting Linux guests in Quickemu from non-functional to a working state.
Commit b9735800f3b2b5d66aec6e984db9d43cb6e9c4c3 should stand alone and resolve #1578. This enables SMM for Linux guests on Linux hosts when Secure Boot has been enabled.
Commit 8add3185e075c466a0d0692d5c87f1d5ad671362 is an example of an initial commit which will probably need wider expansion and partially resolves #413. This configures Quickemu to prefer the `*.secboot.*` version of the `OVMF_VARS` `.fd` file, which is the one which has the Microsoft Platform Keys preloaded into it.
I'm honestly less sure about this second fix as although it makes sense to me (the `*.secboot.*` file is needed to have _full_ Secure Boot working, rather …
> fix: Secure Boot does not work for Linux guests

- quickget
I want to know where big files are stored without opening the browser.
> feat(quickget): Show download path

- quickemu
FreeDOS does ship the Crynwr packet driver package, which does contain an RTL8139 driver. However, you have to install the package after installing FreeDOS, even if you performed a full install. It also seems to lock up for me when attempting to load it.
The PCNet packet driver on the other hand, is installed with a full FreeDOS install, is open source, and does work, at least for me.
> fix: Use the pcnet ethernet device for FreeDOS

- quickget
- Fixes #1628
```
./quickget --check pclinuxos
PASS: pclinuxos-2024.10-kde               https://ftp.fau.de/pclinuxos/pclinuxos/iso/pclinuxos64-kde-2024.10.iso
PASS: pclinuxos-2024.10-kde-darkstar      https://ftp.fau.de/pclinuxos/pclinuxos/iso/pclinuxos64-kde-darkstar-2024.10.iso
PASS: pclinuxos-2024.10-mate              https://ftp.fau.de/pclinuxos/pclinuxos/iso/pclinuxos64-mate-2024-10.iso
PASS: pclinuxos-2024.10-xfce              https://ftp.fau.de/pclinuxos/pclinuxos/iso/pclinuxos64-xfce-2024.10.iso
```
> fix: handle pclinuxos inconsistent naming

- quickget
Bazzite has variants with Steam gaming mode enabled (deck-*). This PR adds them to quickget. Bazzite has also changed its filename formatting to add -amd64, resulting in the previous implementation failing downloads.
> feat: Add Bazzite Deck; fix: Correct bazzite filenames

- quickemu
Correctly check the QEMU version number by striping the Patch version (last digit) and removing dots.
- Fixes #1637
> fix(quickemu): correctly handle version 10.0.0 of QEMU

- flake.nix
The definition of the Nixpkgs overlay exported by `flake.nix` is not conforming to the Flake output schema:
https://wiki.nixos.org/wiki/Flakes#Output_schema
The correct schema for overlays is system independent.
This PR removes the `forEachDefaultSystem` call in its definition.
- Fixes #1633
> fix(nix): Do not use per-system overlays in Flake

- quickget
Solus editions function was using `tail` with default IFS (\n) on the release function that returned space separated values, which doesn't work once there is more than one solus release. We also need to make sure the editions we're matching end in ISO, to ensure that we don't include checksums or other unwanted files.
- Resolves #1656
> fix(solus): update editions function to find correct editions

- quickget
NixOS "plasma" and "gnome" ISOs were unified as "graphical" in 25.05.
This PR has two commits:
1. The first keeps 24.11 support, but VM_PATH is not updated.
2. The second drops 24.11 support, since it will reach EOL on 2025-06-30.
Related links
- Fixes #1672
- https://github.com/NixOS/nixpkgs/pull/355893
- https://nixos.org/blog/announcements/2025/nixos-2505/
After this change
```console
> ./quickget nixos
NixOS
- Credentials: -
- Website:     https://nixos.org/
- Description: Linux distribution based on Nix package manager, tool that takes a unique approach to package management and system configuration.
- Releases:    unstable 25.05
- Editions:    minimal graphical
ERROR! You must specify a release.
> ./quickget nixos 25.05 graphical
Downloading NixOS 25.05 graphical
- URL: …
```
> fix(nixos): support only latest 25.05 

- quickget
Fedora 42 promoted KDE from a spin to a full edition. This breaks the previous jq expression for Fedora 42 KDE. Modify the expression to accept either "Spins" or the specific edition to preserve backwards compatibility while being able to match the new pattern.
- Closes #1669
> fix: Accept edition as fedora variant
